  graph TD
    A[Studiedesign] -->|Manipulera| B[fa:fa-flask Experimentell]
    A -->|Observera| C[fa:fa-eye Observationell]
    B --> |Följ upp| D[fa:fa-hospital Klinisk prövning]
    C --> |Följ INTE upp| E[fa:fa-user-clock Tvärsnittstudie]
    C --> |Följ upp| F[fa:fa-calendar-alt Longitudinell]
    F --> G[fa:fa-users Kohortstudie]
    F --> H[fa:fa-user-friends Fall-kontroll-studie]